### ISSUE TITLE
Ability to defined re-indexed attributes on a model

### ISSUE THREAD

**Issue by robert2d** [agibralter/ts-resque-delta#20]
Absolutely love this project..

Is there a way to only reindex a model when certain attributes are updated rather than reindexing every time a update is made to a model.

Ie; 

  define_index do
    indexes [first_name, last_name], :as => :name, :sortable => true  
    has created_at, updated_at
    has '0', :as => :verification_level, :type => :integer
    set_property :delta => ThinkingSphinx::Deltas::ResqueDelta
  end

I only want to reindex this users delta when their first or last name changes. I know that if any other attribute is updated the users timestamps will change but is it possible to ignore that?

At the moment when a user does a sync to the server from their iphone it updates the lock version on their Player's which causes a reindex which Is unnecessary...

Any help much appreciated.

**Comment by agibralter** [comment]
Thank you for the kind words! I think much, much more credit is due for @freelancing-god and his work on https://github.com/freelancing-god/thinking-sphinx. In fact, I think this sounds like more of an issue for that project since `ThinkingSphinx::Deltas::ResqueDelta` is based on thinking-sphinx's default delta implementation: https://github.com/freelancing-god/thinking-sphinx/blob/master/lib/thinking_sphinx/deltas/default_delta.rb

Since this is all being done in the background though (in Resque), is it such a big problem that the delta indices are being updated more frequently?

**Comment by pat** [comment]
I'm afraid this isn't something that's really possible in Thinking Sphinx, due to lazily included modules and eval'd blocks. It's on my list of features for TS v3, which is a complete rewrite and nearing closer to pre-release:
https://github.com/freelancing-god/thinking-sphinx/tree/edge#limitations

**Comment by agibralter** [comment]
@freelancing-god thanks for the response, Pat! Appreciate it.
