### ISSUE TITLE
Broken with Thinking Sphinx 2.1.0

### ISSUE THREAD

**Issue by tjoneseng** [agibralter/ts-resque-delta#23]
undefined method `client' for #<ThinkingSphinx::Configuration:0x00000005070328>
/home/waiter/apps/production/shared/bundle/ruby/1.9.1/gems/ts-resque-delta-1.2.4/lib/thinking_sphinx/deltas/resque_delta/delta_job.rb:41:in`perform'

**Comment by agibralter** [comment]
Ah, I haven't updated to 2.1.x yet.

@pat, I noticed 1.5.x, 2.1.x and 3.0.x have a new abstraction for Deltas? Any advice on where I should get started for making ts-resque-delta compatible?

**Comment by pat** [comment]
There's three main things that need to change:
- Use `ThinkingSphinx::Deltas::IndexJob.new(delta_index_names).perform` instead of calling to indexer yourself.
- Use `ThinkingSphinx::Deltas::DeleteJob.new(core_index_names, sphinx_document_id).perform` instead of marking records as deleted yourself.
- Add any behaviour that happens before a full index (eg: clearing out queued jobs) to `ThinkingSphinx.before_index_hooks` (an array of procs).

For bonus points, write the code in a manner that works with TS v1/v2 and v3 - it's what the rewritten ts-delayed-delta gem now does. I'm happy to submit pull requests that do all this, but I'm pretty sure I will end up rewriting this gem from scratch (or near enough, given how broadly the all-versions changes will impact things).

**Comment by pat** [comment]
Also: if you're looking for examples on all of this, the [ts-delayed-delta source](https://github.com/pat/ts-delayed-delta) is a great place to start.

**Comment by pat** [comment]
Further to this, perhaps @atlantis can help with the patches as well, given his open pull request.

One other point: with the aforementioned common delta changes, this removes the need for ts-resque-delta to have any Flying Sphinx code - those common job classes (which exist in TS v3 as well) delegate the underlying Sphinx calls appropriately, so it'll work both in standard situations and on Heroku with Flying Sphinx without needing to distinguish between the two in apps using ts-resque-delta.

**Comment by agibralter** [comment]
Ah, very nice, thank you, @pat, for the direction. I'll try to give it a
shot tonight and later this week!

urtak.com / @urtak http://twitter.com/urtak

**Comment by mcspring** [comment]
@atlantis Does the path ready? I met this problem in our production. Much need the fix!

cc @pat

**Comment by atlantis** [comment]
@mcspring I've actually jumped ship to Sunspot/Solr, but you can temporarily use https://github.com/atlantis/ts-resque-delta until @agibralter gets rails 4 support fully baked it... the hacks I made worked well enough for me with Rails 4 (though there's lots more work to be done)

**Comment by mcspring** [comment]
@atlantis Thanks!

**Comment by mattolson** [comment]
Any progress on this? I am keenly interested in getting this gem working with Flying Sphinx, which requires TS 2.1 at a minimum. Ideally, I'd like to use TS 3.

**Comment by pat** [comment]
Closing this, as #25 is about to be released, which includes support for TS v2.1.0.
