### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by hukl** [agibralter/ts-resque-delta#3]
Hey,

so I know the title is somewhat dramatic but I followed the steps from the readme and set up everything accordingly. Resque / Redis is running also. I even ran rake ts:rebuild. Still no delta index jobs are added. Also the rake task tells me that it is a todo and I should run the worker manually but there is no hint in the readme how to do that. There are no errors - nothing happens in terms of resque / delta-indexing. 

What am I doing wrong? Any ideas?

**Comment by agibralter** [comment]
Could you post a gist with a bit more information? Your models, your controllers, your environment.rb... your Gemfile... what server you're running, what you're running from the command line... Otherwise, I'm not sure where to start.

**Comment by hukl** [comment]
I realized that my app still pointed to the production resque / redis install and was queueing the jobs over there - so that why I didn't see them localy. Nonetheless I wonder how to run the workers then since the rake task doesn't work yet.

**Comment by agibralter** [comment]
Ah, sorry. I put a message in here:

https://github.com/agibralter/ts-resque-delta/blob/master/lib/thinking_sphinx/deltas/resque_delta/tasks.rb

Yeah... I'm not sure it's all that useful to have a separate rake task for ts-resque-delta. Since you're probably running resque for other stuff too, the way I suggest you run the ts-resque-delta tasks is by processing tasks on `:ts_delta` queue. Are you running resque for other things?

You'll probably want to do something like this:

```
QUEUE=ts_delta,other,queues,here rake resque:work
```

**Comment by hukl** [comment]
i will investigate further as soon as I find the time. Sorry for my initial message. I was clearly too tired and unfocused :)

I will report back when I have more info.

Kind regards, John

**Comment by agibralter** [comment]
No problem. Let me know if you run into trouble.
